### ISSUE TITLE
Disabling controls does not hide the autoplay start/stop button

### ISSUE THREAD

**Issue by DuckThom** [ganlanyuan/tiny-slider#44]
The `autoplay` option also controls the visibility of the start/stop button, changing `controls` to `false` does not hide that button.

CSS workaround:

```css
div[aria-label="Carousel Pagination"] button[data-action="stop"] {
  display: none;
}
```
