### ISSUE TITLE
Is it possible to have images taking the entire page while captions and  dots (tns-nav) floating on the image?

### ISSUE THREAD

**Issue by WalkerWalker** [ganlanyuan/tiny-slider#513]
Is it possible to have images taking the entire page while captions and dots floating on the image?

Forgive me if it is trivial.  I'm very new to web developing.   It seems like the place of the dots (tns-nav) are not customizable?

**Comment by WebLab-ImpCode** [comment]
> Is it possible to have images taking the entire page while captions and dots floating on the image?
> 
> Forgive me if it is trivial. I'm very new to web developing. It seems like the position of the dots (tns-nav) are not customizable?

You can override class:
```css
.tns-outer .tns-nav {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 10px;
}
```
