### ISSUE TITLE
Slider images are all visible on reload until js is loaded

### ISSUE THREAD

**Issue by c-gross** [ganlanyuan/tiny-slider#599]
__Issue description__:  
Shopware 6.2.3 is using tiny-slider 2.9.2.
During the page load the images are all visible (below each other). Once the js files are loaded, the slider is displayed correctly. Just the active image is visible. The problem is, the hole website is "jumping" on every page load.

I have added a lazy loading plugin to Shopware which is also reducing the issue but it's not completely gone.

__Demo link/slider setting__: intern test

_Tiny-slider version_:   2.9.2
_Browser name && version_:  Tested with Chrome 84.0.4147.105 and Firefox 79.0
_OS name && version_:   Happens on all system. (Tested with MacOS 10.15.6 and Win10 Pro)

**Comment by cpof-tea** [comment]
You can fix this via css (flex on parent and overflow scroll as fallback)

**Comment by kit2m2** [comment]
> You can fix this via css (flex on parent and overflow scroll as fallback)

Can you show an example?

**Comment by cpof-tea** [comment]
```html
<div class="my-slider">
  <div class="my-slider-item">My slide item 1</div>
  <div class="my-slider-item">My slide item 2</div>
  ...
</div>

<div class="my-slider custom">
  <div class="my-slider-item">My slide item 1</div>
  <div class="my-slider-item">My slide item 2</div>
  ...
</div>

<div class="my-slider custom overflow-hidden">
  <div class="my-slider-item">My slide item 1</div>
  <div class="my-slider-item">My slide item 2</div>
  ...
</div>
```
```css
.my-slider:not(.tns-slider) {
  display: flex;

  /* Scroll fallback example */
  overflow-x: auto;
  
  /* Can even add scroll snapping */
  scroll-snap-type: x mandatory;
}

.my-slider-item {
  scroll-snap-align: start;
  user-select: none;

  /**
   * Some sizing. I know, this is experimental,
   * but a shorthand instead of ::before block fallback.
   * Just for understanding the size of slide
   */
  aspect-ratio: 4 / 3;

  /* Just for visual detection of slide */
  border: 1px solid #000;
  border-radius: 4px;

  /* If we need single slide */
  flex-basis: 100%;
  flex-grow: 1;
  flex-shrink: 0;

  /* Media fallbacks */
}

.my-slider.custom:not(.tns-slider) .my-slider-item {
  /**
   * If we need more:
   * 2: flex-basis: 50%;
   * 3: flex-basis: 33.333%;
   * ...and so on
   */
  flex-basis: 33.333%;
}

/* If you don't want scroll fallback, then */
.my-slider.overflow-hidden:not(.tns-slider) {
  overflow: hidden;
}
```
[Demo](https://codepen.io/cpof_tea/details/QWEjRrd)
Other margins and paddings you can handle by yourself. There's still gonna be a small layout thrashing (especially with scroll fallback), but it better to have fallbacks on simple sliders, I think.
