### ISSUE TITLE
Sliders flickering on Safari

### ISSUE THREAD

**Issue by marcolink** [ganlanyuan/tiny-slider#683]
__Issue description__:  I Observed that slider items are flickering on Safari. The problem has been on observed on safari.

__Demo link/slider setting__: https://codesandbox.io/s/d0yoz
(It's a random example I found on the codesandbox)

_Tiny-slider version_:   tested with 2.8.8 - 2.9.3
_Browser name && version_:  Safar 14.0.3
_OS name && version_:   OSX 10.15.7

**Comment by dijkermans** [comment]
Yes, it's very noticeable on the Customize demo slider. It kinda looks like a loazyload thing but it flickers after it's loaded and shown. Half of the image or 2 even images flicker after sliding.

ios 14.4 / ipad 2017 / safari + Chrome

**Comment by dijkermans** [comment]
I've seen these kind of problems before on Safari and it seems to be related with Translate3D, which is being used for the sliding effect.

**Comment by marcolink** [comment]
@dijkermans any known "hacks" to prevent this? unfortunately, I'm more a JS than CSS person 😬

**Comment by dijkermans** [comment]
Hi, try this CSS on the slides and/or img:

-webkit-backface-visibility: hidden;
-webkit-perspective: 1000;

Please let me know if it works.

I guess the best fix is to use TranslateX instead of Translate3D, but 3d renders faster.

**Comment by marcolink** [comment]
@dijkermans 🙇 

```css
.tns-item, tns-item img {
  perspective: 1000;
  backface-visibility: hidden;
  transform: translate3d(0, 0, 0);
  -webkit-perspective: 1000;
  -webkit-backface-visibility: hidden;
  -webkit-transform: translate3d(0, 0, 0);
}
```
... id did fix the problem for me 😎

**Comment by marcolink** [comment]
btw I think only the `webkit` namespaces props are relevant

**Comment by dijkermans** [comment]
I think it should be like this:

-webkit-backface-visibility: hidden;
-moz-backface-visibility: hidden;
backface-visibility: hidden;	

btw, is this one really required?:  -webkit-transform: translate3d(0, 0, 0);

Please try and share which lines were required to fix it.

**Comment by marcolink** [comment]
`-webkit-transform: translate3d(0, 0, 0);` finally fixed it for me

**Comment by marcolink** [comment]
Ok, I double-checked, the minimum required CSS (in my case) is:

```css
.tns-item {
  -webkit-transform: translate3d(0, 0, 0);
}
```
